// Header helpers the store needs when it ingests Gmail metadata. Kept tiny and
// dependency-free; the gmail package has the fuller MIME toolkit.

import type { GmailHeaderInput, GmailPartInput } from "./types.js";

export interface Address {
  email: string;
  name: string;
}

export function headerValue(headers: GmailHeaderInput[] | undefined, name: string): string {
  const lower = name.toLowerCase();
  return headers?.find((h) => h.name.toLowerCase() === lower)?.value ?? "";
}

const ADDR_RE = /(?:"?([^"<]*)"?\s*)?<([^>]+)>|([^\s,<>]+@[^\s,<>]+)/g;

/** Parses a To/From style header into address objects. Names are unquoted; emails lowercased. */
export function parseAddressList(value: string): Address[] {
  const out: Address[] = [];
  if (!value) return out;
  for (const m of value.matchAll(ADDR_RE)) {
    const email = (m[2] ?? m[3] ?? "").trim().toLowerCase();
    if (!email) continue;
    const name = (m[1] ?? "").trim().replace(/^"|"$/g, "");
    out.push({ email, name });
  }
  return out;
}

const REPLY_PREFIX = /^\s*((re|fwd?|aw|sv)\s*:\s*)+/i;

export function normalizeSubject(subject: string): string {
  return (subject || "").replace(REPLY_PREFIX, "").trim().toLowerCase();
}

export function isAutoGenerated(headers: GmailHeaderInput[] | undefined, fromEmail: string, subject: string): boolean {
  const auto = headerValue(headers, "Auto-Submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  if (headerValue(headers, "X-Autoreply") || headerValue(headers, "X-Autorespond")) return true;
  if (headerValue(headers, "Precedence").toLowerCase() === "auto_reply") return true;
  if (/^(mailer-daemon|postmaster|no-?reply|do-?not-?reply)@/.test(fromEmail)) return true;
  if (/^(out of office|automatic reply|delivery status notification|undeliverable)/i.test(subject)) return true;
  return false;
}

export function senderType(headers: GmailHeaderInput[] | undefined, fromEmail: string): "role-address" | "machine" | "person" {
  if (/^(info|hello|hi|team|sales|support|billing|accounts|admin|office|contact|noreply|no-reply|notifications?|alerts?|updates?|newsletter|marketing)@/.test(fromEmail)) {
    return "role-address";
  }
  if (headerValue(headers, "List-Id") || headerValue(headers, "List-Unsubscribe")) return "machine";
  return "person";
}

/**
 * Whether a message carries a file someone would open, as opposed to pieces of its own layout.
 *
 * Only an explicit Content-Disposition: inline counts as layout here. A Content-ID does not, and
 * treating it as one hid real attachments: Gmail stamps a Content-ID on every attachment of a
 * message composed in Gmail, so a CV sent from Gmail was classed as layout and vanished from the
 * paperclip and the With attachments view.
 *
 * The MIME walker can do better, because it has the HTML and can check whether anything actually
 * points at the Content-ID with cid:. This runs on metadata, where that is not available, so it
 * asks only the question it can answer. Erring toward "this is a file" is the right way round: a
 * layout image listed as an attachment is untidy, a hidden CV is a lost candidate.
 */
export function partHasAttachment(part: GmailPartInput | undefined): boolean {
  if (!part) return false;
  if (part.filename && part.body?.attachmentId && !isInlinePart(part)) return true;
  return (part.parts ?? []).some(partHasAttachment);
}

function isInlinePart(part: GmailPartInput): boolean {
  for (const h of part.headers ?? []) {
    if ((h.name ?? "").toLowerCase() !== "content-disposition") continue;
    return (h.value ?? "").toLowerCase().trimStart().startsWith("inline");
  }
  return false;
}


const NAMED_ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0" };

/** Gmail's snippets are HTML-escaped; store them as text so the list never shows &#39; or &amp;. */
export function decodeEntities(input: string): string {
  return input.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, body: string) => {
    const b = body.toLowerCase();
    if (b.startsWith("#x")) { const cp = parseInt(b.slice(2), 16); return Number.isFinite(cp) ? String.fromCodePoint(cp) : m; }
    if (b.startsWith("#")) { const cp = parseInt(b.slice(1), 10); return Number.isFinite(cp) ? String.fromCodePoint(cp) : m; }
    return NAMED_ENTITIES[b] ?? m;
  });
}
