// Header helpers the store needs when it ingests Gmail metadata. Kept tiny and
// dependency-free; the gmail package has the fuller MIME toolkit.

import type { GmailHeaderInput, GmailPartInput } from "./types.js";

export interface Address {
  email: string;
  name: string;
}

export function headerValue(headers: GmailHeaderInput[] | undefined, name: string): string {
  const lower = name.toLowerCase();
  return headers?.find((h) => h.name.toLowerCase() === lower)?.value ?? "";
}

/** Parses a To/From style header into address objects. Names are unquoted; emails lowercased. */
/**
 * A header's addresses, one entry per person.
 *
 * The old regex let a name run across commas. "a@b.com, Jane Roe <jane@x.com>" came out as one
 * entry named "a@b.com, Jane Roe", and "x@y.com, Aliki" as a name of ", Aliki": a sixth of the
 * stored recipients carried another address, or a stray comma, inside their name, and the
 * recipient suggester then showed rows that looked like group chats. The header is split on the
 * commas that sit outside quotes and angle brackets first, and each piece is parsed on its own. A
 * name that contains an address is not a name and is dropped.
 */
export function parseAddressList(value: string): Address[] {
  const out: Address[] = [];
  if (!value) return out;
  for (const piece of splitAddresses(value)) {
    const m = /^(?:"?([^"<]*?)"?\s*)?<([^>]+)>$/.exec(piece) ?? /^([^\s<>]+@[^\s<>]+)$/.exec(piece);
    if (!m) continue;
    const email = (m[2] ?? m[1] ?? "").trim().toLowerCase();
    if (!email.includes("@")) continue;
    const rawName = m[2] ? (m[1] ?? "") : "";
    out.push({ email, name: cleanName(rawName, email) });
  }
  return out;
}

/** Splits on commas that separate addresses, never on ones inside quotes or angle brackets. */
function splitAddresses(value: string): string[] {
  const pieces: string[] = [];
  let cur = "";
  let quoted = false;
  let depth = 0;
  for (const ch of value) {
    if (ch === '"') quoted = !quoted;
    else if (!quoted && ch === "<") depth++;
    else if (!quoted && ch === ">") depth = Math.max(0, depth - 1);
    if (ch === "," && !quoted && depth === 0) {
      pieces.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  pieces.push(cur);
  return pieces.map((p) => p.trim()).filter(Boolean);
}

/** A display name, or nothing: never an address, never a leftover comma, never the email again. */
export function cleanName(raw: string, email: string): string {
  const name = raw.trim().replace(/^"|"$/g, "").replace(/^[\s,;]+|[\s,;]+$/g, "").trim();
  if (!name || name.includes("@") || name.toLowerCase() === email) return "";
  return name;
}

const REPLY_PREFIX = /^\s*((re|fwd?|aw|sv)\s*:\s*)+/i;

export function normalizeSubject(subject: string): string {
  return (subject || "").replace(REPLY_PREFIX, "").trim().toLowerCase();
}

export function isAutoGenerated(headers: GmailHeaderInput[] | undefined, fromEmail: string, subject: string): boolean {
  const auto = headerValue(headers, "Auto-Submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  if (headerValue(headers, "X-Autoreply") || headerValue(headers, "X-Autorespond")) return true;
  if (headerValue(headers, "Precedence").toLowerCase() === "auto_reply") return true;
  if (/^(mailer-daemon|postmaster|no-?reply|do-?not-?reply)@/.test(fromEmail)) return true;
  if (/^(out of office|automatic reply|delivery status notification|undeliverable)/i.test(subject)) return true;
  return false;
}

export function senderType(headers: GmailHeaderInput[] | undefined, fromEmail: string): "role-address" | "machine" | "person" {
  if (/^(info|hello|hi|team|sales|support|billing|accounts|admin|office|contact|noreply|no-reply|notifications?|alerts?|updates?|newsletter|marketing)@/.test(fromEmail)) {
    return "role-address";
  }
  if (headerValue(headers, "List-Id") || headerValue(headers, "List-Unsubscribe")) return "machine";
  return "person";
}

/**
 * Whether a message carries a file someone would open, as opposed to pieces of its own layout.
 *
 * Only an explicit Content-Disposition: inline counts as layout here. A Content-ID does not, and
 * treating it as one hid real attachments: Gmail stamps a Content-ID on every attachment of a
 * message composed in Gmail, so a CV sent from Gmail was classed as layout and vanished from the
 * paperclip and the With attachments view.
 *
 * The MIME walker can do better, because it has the HTML and can check whether anything actually
 * points at the Content-ID with cid:. This runs on metadata, where that is not available, so it
 * asks only the question it can answer. Erring toward "this is a file" is the right way round: a
 * layout image listed as an attachment is untidy, a hidden CV is a lost candidate.
 */
export function partHasAttachment(part: GmailPartInput | undefined): boolean {
  if (!part) return false;
  if (part.filename && part.body?.attachmentId && !isInlinePart(part)) return true;
  return (part.parts ?? []).some(partHasAttachment);
}

function isInlinePart(part: GmailPartInput): boolean {
  for (const h of part.headers ?? []) {
    if ((h.name ?? "").toLowerCase() !== "content-disposition") continue;
    return (h.value ?? "").toLowerCase().trimStart().startsWith("inline");
  }
  return false;
}


const NAMED_ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0" };

/** Gmail's snippets are HTML-escaped; store them as text so the list never shows &#39; or &amp;. */
export function decodeEntities(input: string): string {
  return input.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, body: string) => {
    const b = body.toLowerCase();
    if (b.startsWith("#x")) { const cp = parseInt(b.slice(2), 16); return Number.isFinite(cp) ? String.fromCodePoint(cp) : m; }
    if (b.startsWith("#")) { const cp = parseInt(b.slice(1), 10); return Number.isFinite(cp) ? String.fromCodePoint(cp) : m; }
    return NAMED_ENTITIES[b] ?? m;
  });
}
