#!/usr/bin/env node
// Copies the brand system from arcforma-brand into apps/desktop/public/brand/.
// The brand is consumed verbatim: tokens, fonts, wordmark files, and the
// dither runtime. The only edit made on the way in is a filename rewrite for
// the variable fonts, because Vite and file:// both choke on square brackets
// in URLs. Every rename is logged and mirrored into the copied fonts.css.

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const src = process.env.ARCFORMA_BRAND_DIR || path.join(os.homedir(), "Projects", "arcforma-brand");
const dest = path.join(repoRoot, "apps", "desktop", "public", "brand");

function fail(msg) {
  console.error(`sync-brand: ${msg}`);
  process.exit(1);
}

if (!fs.existsSync(src)) fail(`brand repo not found at ${src}`);
for (const required of ["styles.css", "fonts/fonts.css", "assets/logos", "animation/ds-motion.js"]) {
  if (!fs.existsSync(path.join(src, required))) fail(`missing ${required} in ${src}`);
}

fs.rmSync(dest, { recursive: true, force: true });
fs.mkdirSync(path.join(dest, "fonts"), { recursive: true });
fs.mkdirSync(path.join(dest, "logos"), { recursive: true });

const log = (line) => console.log(`sync-brand: ${line}`);

// Bracketed variable-font names become hyphenated: Inter[opsz,wght].ttf -> Inter-opsz-wght.ttf
function safeFontName(name) {
  return name.replace(/\[/g, "-").replace(/,/g, "-").replace(/\]/g, "");
}

const renames = new Map();
for (const entry of fs.readdirSync(path.join(src, "fonts"))) {
  const from = path.join(src, "fonts", entry);
  if (entry.endsWith(".ttf")) {
    const to = safeFontName(entry);
    fs.copyFileSync(from, path.join(dest, "fonts", to));
    if (to !== entry) {
      renames.set(entry, to);
      log(`renamed fonts/${entry} -> fonts/${to}`);
    } else {
      log(`copied fonts/${entry}`);
    }
  } else if (/^OFL-.*\.txt$/.test(entry)) {
    fs.copyFileSync(from, path.join(dest, "fonts", entry));
    log(`copied fonts/${entry}`);
  }
}

let fontsCss = fs.readFileSync(path.join(src, "fonts", "fonts.css"), "utf8");
for (const [from, to] of renames) {
  const before = fontsCss;
  fontsCss = fontsCss.split(`url("./${from}")`).join(`url("./${to}")`);
  if (before === fontsCss) fail(`fonts.css has no url() for ${from}; refusing to ship a broken face`);
}
if (/\[|\]/.test(fontsCss.match(/url\([^)]*\)/g)?.join("") || "")) fail("bracketed url() survived the rewrite");
fs.writeFileSync(path.join(dest, "fonts", "fonts.css"), fontsCss);
log("wrote fonts/fonts.css with rewritten url() entries");

// styles.css imports ./fonts/fonts.css, which resolves at /brand/fonts/fonts.css. Keep it
// relative; only rewrite if the source ever changes to a path that would not resolve.
let stylesCss = fs.readFileSync(path.join(src, "styles.css"), "utf8");
const importRe = /@import\s+url\(\s*["']?([^"')]+)["']?\s*\)\s*;/;
const m = stylesCss.match(importRe);
if (m && m[1] !== "./fonts/fonts.css") {
  stylesCss = stylesCss.replace(importRe, '@import url("./fonts/fonts.css");');
  log(`rewrote @import ${m[1]} -> ./fonts/fonts.css`);
}
fs.writeFileSync(path.join(dest, "styles.css"), stylesCss);
log("copied styles.css");

for (const entry of fs.readdirSync(path.join(src, "assets", "logos"))) {
  if (!entry.endsWith(".svg")) continue;
  fs.copyFileSync(path.join(src, "assets", "logos", entry), path.join(dest, "logos", entry));
  log(`copied logos/${entry}`);
}

fs.copyFileSync(path.join(src, "animation", "ds-motion.js"), path.join(dest, "ds-motion.js"));
log("copied ds-motion.js");

fs.writeFileSync(
  path.join(dest, "SOURCE.txt"),
  `Generated by scripts/sync-brand.mjs from ${src} on ${new Date().toISOString()}. Do not edit; rerun the sync.\n`
);
log(`done -> ${path.relative(repoRoot, dest)}`);
