import { decodeEntities } from "../mail-headers.js";
import type { Db } from "../db.js";
import { transaction } from "../db.js";
import { headerValue, isAutoGenerated, parseAddressList, partHasAttachment, senderType } from "../mail-headers.js";
import { setThreadLabels } from "./labels.js";
import type { GmailMessageInput, MessageBodyRow, MessageRow, ThreadRow } from "../types.js";

const STORED_HEADERS = [
  "From",
  "To",
  "Cc",
  "Bcc",
  "Reply-To",
  "Subject",
  "Date",
  "Message-ID",
  "In-Reply-To",
  "References",
  "List-Id",
  "List-Unsubscribe",
  "List-Unsubscribe-Post",
  "Precedence",
  "Auto-Submitted",
  "X-Autoreply",
  "Content-Type",
];

export interface UpsertContext {
  /** Lowercased addresses the account can send from; decides message direction. */
  ownerAddresses?: string[];
}

function labelsOf(m: GmailMessageInput): string[] {
  return Array.from(new Set(m.labelIds ?? []));
}

/** Writes one Gmail message (metadata or full) into messages and messages_fts. Does not touch the thread row. */
export function upsertMessage(db: Db, accountId: string, m: GmailMessageInput, ctx: UpsertContext = {}): void {
  const headers = m.payload?.headers ?? [];
  const from = parseAddressList(headerValue(headers, "From"))[0] ?? { email: "", name: "" };
  const to = parseAddressList(headerValue(headers, "To"));
  const cc = parseAddressList(headerValue(headers, "Cc"));
  const bcc = parseAddressList(headerValue(headers, "Bcc"));
  const subject = headerValue(headers, "Subject");
  const labels = labelsOf(m);
  const owners = new Set((ctx.ownerAddresses ?? []).map((a) => a.toLowerCase()));
  const direction: "in" | "out" = labels.includes("SENT") || owners.has(from.email) ? "out" : "in";
  const stored: Record<string, string> = {};
  for (const name of STORED_HEADERS) {
    const v = headerValue(headers, name);
    if (v) stored[name] = v;
  }
  const now = Date.now();
  // fts_id is handed out once, on insert, and never touched by the update
  // branch: it is the FTS rowid and must outlive any VACUUM.
  db.prepare(
    `INSERT INTO messages (account_id, id, thread_id, internal_date, from_email, from_name, to_json, cc_json, bcc_json,
       subject, snippet, message_id_header, in_reply_to, references_header, label_ids_json, headers_json, has_attachments,
       size_estimate, is_auto, sender_type, direction, history_id, updated_at, fts_id)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, (SELECT COALESCE(MAX(fts_id), 0) + 1 FROM messages))
     ON CONFLICT(account_id, id) DO UPDATE SET
       thread_id = excluded.thread_id, internal_date = excluded.internal_date, from_email = excluded.from_email,
       from_name = excluded.from_name, to_json = excluded.to_json, cc_json = excluded.cc_json, bcc_json = excluded.bcc_json,
       subject = excluded.subject, snippet = excluded.snippet, message_id_header = excluded.message_id_header,
       in_reply_to = excluded.in_reply_to, references_header = excluded.references_header,
       label_ids_json = excluded.label_ids_json, headers_json = excluded.headers_json,
       has_attachments = MAX(messages.has_attachments, excluded.has_attachments), size_estimate = excluded.size_estimate,
       is_auto = excluded.is_auto, sender_type = excluded.sender_type, direction = excluded.direction,
       history_id = excluded.history_id, updated_at = excluded.updated_at`
  ).run(
    accountId,
    m.id,
    m.threadId,
    Number(m.internalDate ?? 0),
    from.email,
    from.name,
    JSON.stringify(to),
    JSON.stringify(cc),
    JSON.stringify(bcc),
    subject,
    decodeEntities(m.snippet ?? ""),
    headerValue(headers, "Message-ID") || null,
    headerValue(headers, "In-Reply-To") || null,
    headerValue(headers, "References") || null,
    JSON.stringify(labels),
    JSON.stringify(stored),
    partHasAttachment(m.payload) || m.payload?.mimeType === "multipart/mixed" ? 1 : 0,
    m.sizeEstimate ?? null,
    isAutoGenerated(headers, from.email, subject) ? 1 : 0,
    senderType(headers, from.email),
    direction,
    m.historyId ?? null,
    now
  );
  indexMessage(db, accountId, m.id);
}

/** Rebuilds the FTS row for a message from messages plus message_bodies, keyed by the message's fts_id. */
export function indexMessage(db: Db, accountId: string, messageId: string): void {
  const row = db
    .prepare(
      `SELECT m.fts_id AS rid, m.thread_id, m.subject, m.from_email, m.from_name, m.to_json, m.cc_json, m.snippet, b.text, b.html
       FROM messages m LEFT JOIN message_bodies b ON b.account_id = m.account_id AND b.message_id = m.id
       WHERE m.account_id = ? AND m.id = ?`
    )
    .get(accountId, messageId) as
    | { rid: number; thread_id: string; subject: string; from_email: string; from_name: string; to_json: string; cc_json: string; snippet: string; text: string | null; html: string | null }
    | undefined;
  if (!row) return;
  const recipients = [...(JSON.parse(row.to_json) as Array<{ email: string; name: string }>), ...(JSON.parse(row.cc_json) as Array<{ email: string; name: string }>)]
    .map((a) => `${a.name} ${a.email}`)
    .join(" ");
  const body = row.text ?? (row.html ? stripHtml(row.html) : row.snippet);
  db.prepare("DELETE FROM messages_fts WHERE rowid = ?").run(row.rid);
  db.prepare("INSERT INTO messages_fts (rowid, account_id, thread_id, message_id, subject, from_text, to_text, body) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").run(
    row.rid,
    accountId,
    row.thread_id,
    messageId,
    row.subject,
    `${row.from_name} ${row.from_email}`,
    recipients,
    body
  );
}

export function stripHtml(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

export function getMessage(db: Db, accountId: string, id: string): MessageRow | null {
  return (db.prepare("SELECT * FROM messages WHERE account_id = ? AND id = ?").get(accountId, id) as unknown as MessageRow | undefined) ?? null;
}

/**
 * Messages of a thread in order. Gmail keeps drafts inside the thread as DRAFT-labelled messages;
 * they are not mail and never show as sent, so they are excluded unless a caller asks for them.
 */
export function listThreadMessages(db: Db, accountId: string, threadId: string, opts: { includeDrafts?: boolean } = {}): MessageRow[] {
  const rows = db.prepare("SELECT * FROM messages WHERE account_id = ? AND thread_id = ? ORDER BY internal_date, id").all(accountId, threadId) as unknown as MessageRow[];
  return opts.includeDrafts ? rows : rows.filter((m) => !isDraftMessage(m));
}

export function isDraftMessage(m: Pick<MessageRow, "label_ids_json">): boolean {
  try { return (JSON.parse(m.label_ids_json) as string[]).includes("DRAFT"); } catch { return false; }
}

/** Drops every FTS row and writes one per message. Used by the schema 3 migration; safe to call any time. */
export function reindexAllMessages(db: Db): number {
  db.exec("DELETE FROM messages_fts");
  const rows = db.prepare("SELECT account_id, id FROM messages").all() as Array<{ account_id: string; id: string }>;
  for (const r of rows) indexMessage(db, r.account_id, r.id);
  return rows.length;
}

export function deleteMessage(db: Db, accountId: string, id: string): string | null {
  const row = db.prepare("SELECT fts_id AS rid, thread_id FROM messages WHERE account_id = ? AND id = ?").get(accountId, id) as { rid: number; thread_id: string } | undefined;
  if (!row) return null;
  transaction(db, () => {
    db.prepare("DELETE FROM messages_fts WHERE rowid = ?").run(row.rid);
    db.prepare("DELETE FROM messages WHERE account_id = ? AND id = ?").run(accountId, id);
  });
  return row.thread_id;
}

export function setMessageLabels(db: Db, accountId: string, id: string, labelIds: string[]): void {
  db.prepare("UPDATE messages SET label_ids_json = ?, updated_at = ? WHERE account_id = ? AND id = ?").run(JSON.stringify(Array.from(new Set(labelIds))), Date.now(), accountId, id);
}

export interface BodyInput {
  html?: string | null;
  text?: string | null;
  attachments?: unknown[];
  /** The parsed VEVENT of an invitation, when the message carried one. */
  calendar?: unknown | null;
}

export function saveBody(db: Db, accountId: string, messageId: string, body: BodyInput): void {
  transaction(db, () => {
    db.prepare(
      `INSERT INTO message_bodies (account_id, message_id, html, text, attachments_json, calendar_json, fetched_at) VALUES (?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(account_id, message_id) DO UPDATE SET html = excluded.html, text = excluded.text,
         attachments_json = excluded.attachments_json, calendar_json = excluded.calendar_json, fetched_at = excluded.fetched_at`
    ).run(accountId, messageId, body.html ?? null, body.text ?? null, JSON.stringify(body.attachments ?? []), body.calendar ? JSON.stringify(body.calendar) : null, Date.now());
    // Only files someone could open count. Inline images are the message's own layout, and counting
    // them lit the paperclip on mail with nothing to show for it.
    const files = (body.attachments ?? []).filter((a) => (a as { inline?: boolean }).inline !== true);
    if (files.length > 0) {
      db.prepare("UPDATE messages SET has_attachments = 1 WHERE account_id = ? AND id = ?").run(accountId, messageId);
    }
    indexMessage(db, accountId, messageId);
  });
}

export function getBody(db: Db, accountId: string, messageId: string): MessageBodyRow | null {
  return (db.prepare("SELECT * FROM message_bodies WHERE account_id = ? AND message_id = ?").get(accountId, messageId) as unknown as MessageBodyRow | undefined) ?? null;
}

export function listBodies(db: Db, accountId: string, threadId: string): MessageBodyRow[] {
  return db
    .prepare(
      `SELECT b.* FROM message_bodies b JOIN messages m ON m.account_id = b.account_id AND m.id = b.message_id
       WHERE m.account_id = ? AND m.thread_id = ?`
    )
    .all(accountId, threadId) as unknown as MessageBodyRow[];
}

/** Recomputes the denormalized thread row and thread_labels from its messages. Returns null, with the row removed, when the thread has no live (non-draft) messages. */
export function recomputeThread(db: Db, accountId: string, threadId: string, opts: { keepSortAt?: boolean } = {}): ThreadRow | null {
  const all = listThreadMessages(db, accountId, threadId, { includeDrafts: true });
  if (all.length === 0) {
    db.prepare("DELETE FROM threads WHERE account_id = ? AND id = ?").run(accountId, threadId);
    return null;
  }
  // Drafts never drive the thread's subject, snippet, participants, dates, or count. A thread
  // that is only a draft (a new message not yet sent, or a reply whose original went away) is
  // not mail: it would list under All Mail with the draft's subject and open empty, since the
  // draft itself lives in the drafts table. The row goes; the cascade takes its messages.
  const live = all.filter((m) => !isDraftMessage(m));
  if (live.length === 0) {
    db.prepare("DELETE FROM threads WHERE account_id = ? AND id = ?").run(accountId, threadId);
    return null;
  }
  const msgs = live;
  // Gmail history is per message. A thread is unread, starred, or in the
  // inbox when any live message is; a message in TRASH or SPAM no longer
  // counts, and the thread itself only carries TRASH or SPAM when every
  // message does. Otherwise trashing one reply would hide the whole thread.
  const labels = new Set<string>();
  const participants = new Map<string, string>();
  let unread = 0;
  let starred = 0;
  let inInbox = 0;
  let attachments = 0;
  let lastIn: number | null = null;
  let lastOut: number | null = null;
  let allTrash = true;
  let allSpam = true;
  for (const m of msgs) {
    const ls = JSON.parse(m.label_ids_json) as string[];
    const hidden = ls.includes("TRASH") || ls.includes("SPAM");
    if (!ls.includes("TRASH")) allTrash = false;
    if (!ls.includes("SPAM")) allSpam = false;
    for (const l of ls) if (l !== "TRASH" && l !== "SPAM") labels.add(l);
    if (!hidden) {
      if (ls.includes("UNREAD")) unread = 1;
      if (ls.includes("STARRED")) starred = 1;
      if (ls.includes("INBOX")) inInbox = 1;
    }
    if (m.has_attachments) attachments = 1;
    if (m.from_email && !participants.has(m.from_email)) participants.set(m.from_email, m.from_name);
    if (m.direction === "in") lastIn = Math.max(lastIn ?? 0, m.internal_date);
    else lastOut = Math.max(lastOut ?? 0, m.internal_date);
  }
  if (allTrash) labels.add("TRASH");
  if (allSpam) labels.add("SPAM");
  const first = msgs[0]!;
  const last = msgs[msgs.length - 1]!;
  const subject = msgs.find((m) => m.subject)?.subject ?? "";
  const existing = db.prepare("SELECT sort_at, history_id FROM threads WHERE account_id = ? AND id = ?").get(accountId, threadId) as { sort_at: number; history_id: string | null } | undefined;
  const sortAt = opts.keepSortAt && existing ? Math.max(existing.sort_at, last.internal_date) : last.internal_date;
  const now = Date.now();
  db.prepare(
    `INSERT INTO threads (account_id, id, subject, snippet, participants_json, first_message_at, last_message_at, sort_at, message_count,
       unread, starred, in_inbox, has_attachments, last_inbound_at, last_outbound_at, history_id, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(account_id, id) DO UPDATE SET subject = excluded.subject, snippet = excluded.snippet,
       participants_json = excluded.participants_json, first_message_at = excluded.first_message_at,
       last_message_at = excluded.last_message_at, sort_at = excluded.sort_at, message_count = excluded.message_count,
       unread = excluded.unread, starred = excluded.starred, in_inbox = excluded.in_inbox, has_attachments = excluded.has_attachments,
       last_inbound_at = excluded.last_inbound_at, last_outbound_at = excluded.last_outbound_at,
       history_id = COALESCE(excluded.history_id, threads.history_id), updated_at = excluded.updated_at`
  ).run(
    accountId,
    threadId,
    subject,
    last.snippet,
    JSON.stringify(Array.from(participants, ([email, name]) => ({ email, name }))),
    first.internal_date,
    last.internal_date,
    sortAt,
    msgs.length,
    unread,
    starred,
    inInbox,
    attachments,
    lastIn,
    lastOut,
    last.history_id ?? existing?.history_id ?? null,
    now
  );
  setThreadLabels(db, accountId, threadId, labels);
  return db.prepare("SELECT * FROM threads WHERE account_id = ? AND id = ?").get(accountId, threadId) as unknown as ThreadRow;
}
