// Deterministic mail rules, ported from mailroom/src/normalize.js onto Gmail
// API message shapes. These run before any model sees a message.

import { hasCalendarPart, header, parseAddressList, type GmailMessage } from "./mime.js";

const REPLY_PREFIX = /^\s*((re|fwd?|aw|sv)\s*:\s*)+/i;

export function normalizeSubject(subject: string | undefined | null): string {
  return (subject || "").replace(REPLY_PREFIX, "").trim().toLowerCase();
}

export function fromAddress(m: GmailMessage): string {
  return parseAddressList(header(m, "From"))[0]?.email ?? "";
}

export function isAutoGenerated(m: GmailMessage): boolean {
  const auto = header(m, "Auto-Submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  if (header(m, "X-Autoreply") || header(m, "X-Autorespond")) return true;
  if (header(m, "Precedence").toLowerCase() === "auto_reply") return true;
  const from = fromAddress(m);
  if (/^(mailer-daemon|postmaster|no-?reply|do-?not-?reply)@/.test(from)) return true;
  const subj = header(m, "Subject").toLowerCase();
  if (/^(out of office|automatic reply|delivery status notification|undeliverable)/.test(subj)) return true;
  return false;
}

export type SenderType = "role-address" | "machine" | "person";

export function senderType(m: GmailMessage): SenderType {
  const from = fromAddress(m);
  if (/^(info|hello|hi|team|sales|support|billing|accounts|admin|office|contact|noreply|no-reply|notifications?|alerts?|updates?|newsletter|marketing)@/.test(from)) {
    return "role-address";
  }
  if (header(m, "List-Id") || header(m, "List-Unsubscribe")) return "machine";
  return "person";
}

export type RuleType = "newsletters" | "calendar" | "notifications" | "receipts";

const NOTIFICATION_SENDERS = /@(github\.com|slack\.com|notion\.so|linear\.app|figma\.com|render\.com|vercel\.com|atlassian\.net|asana\.com|calendly\.com|zoom\.us|docusign\.(net|com)|mail\.notion\.so|em\.granola\.ai)$/i;
const RECEIPT_SUBJECT = /\b(receipt|invoice|your order|order confirmation|payment (received|confirmation)|has been paid|statement is (ready|available))\b/i;
const RECEIPT_SENDERS = /^(receipts?|invoices?|billing|payments?|orders?|no-?reply\+receipts?)@|@(stripe\.com|mercury\.com|paypal\.com|squareup\.com|shopify\.com|amazon\.com)$/i;

/** Subjects calendar systems generate for invitations and replies. */
const CALENDAR_SUBJECT = /^\s*(invitation|updated invitation|accepted|declined|tentatively accepted|tentative|canceled event|cancelled event|new event|event update|reminder)\b/i;
const CALENDAR_SENDERS = /^(calendar-notification@google\.com|calendar-server@|.*@calendar\.google\.com|no-?reply@calendly\.com|.*@cal\.com)$/i;

/**
 * A calendar object alone is not enough: a person who writes "here is the invite" and attaches
 * an .ics is having a conversation, and the thread belongs with them, not under Calendar. Calendar
 * means the message itself is a calendar notice: generated by a calendar system, or carrying an
 * invitation-style subject, or auto-submitted.
 */
export function isCalendarNotice(m: GmailMessage): boolean {
  if (!hasCalendarPart(m.payload)) return false;
  const from = fromAddress(m);
  if (CALENDAR_SENDERS.test(from)) return true;
  if (CALENDAR_SUBJECT.test(header(m, "Subject"))) return true;
  return isAutoGenerated(m);
}

/** First-pass type from headers alone. Null means the rules have no opinion. */
export function ruleType(m: GmailMessage): RuleType | null {
  if (isCalendarNotice(m)) return "calendar";
  const from = fromAddress(m);
  const subject = header(m, "Subject");
  if (RECEIPT_SENDERS.test(from) || RECEIPT_SUBJECT.test(subject)) return "receipts";
  if (header(m, "List-Unsubscribe") || header(m, "List-Id")) {
    return NOTIFICATION_SENDERS.test(from) ? "notifications" : "newsletters";
  }
  if (header(m, "Precedence").toLowerCase() === "bulk" || NOTIFICATION_SENDERS.test(from)) return "notifications";
  return null;
}
