// Deterministic mail rules, ported from mailroom/src/normalize.js onto Gmail
// API message shapes. These run before any model sees a message.

import { hasCalendarPart, header, parseAddressList, type GmailMessage } from "./mime.js";

const REPLY_PREFIX = /^\s*((re|fwd?|aw|sv)\s*:\s*)+/i;

export function normalizeSubject(subject: string | undefined | null): string {
  return (subject || "").replace(REPLY_PREFIX, "").trim().toLowerCase();
}

export function fromAddress(m: GmailMessage): string {
  return parseAddressList(header(m, "From"))[0]?.email ?? "";
}

export function isAutoGenerated(m: GmailMessage): boolean {
  const auto = header(m, "Auto-Submitted");
  if (auto && auto.toLowerCase() !== "no") return true;
  if (header(m, "X-Autoreply") || header(m, "X-Autorespond")) return true;
  if (header(m, "Precedence").toLowerCase() === "auto_reply") return true;
  const from = fromAddress(m);
  if (/^(mailer-daemon|postmaster|no-?reply|do-?not-?reply)@/.test(from)) return true;
  const subj = header(m, "Subject").toLowerCase();
  if (/^(out of office|automatic reply|delivery status notification|undeliverable)/.test(subj)) return true;
  return false;
}

export type SenderType = "role-address" | "machine" | "person";

export function senderType(m: GmailMessage): SenderType {
  const from = fromAddress(m);
  if (/^(info|hello|hi|team|sales|support|billing|accounts|admin|office|contact|noreply|no-reply|notifications?|alerts?|updates?|newsletter|marketing)@/.test(from)) {
    return "role-address";
  }
  if (header(m, "List-Id") || header(m, "List-Unsubscribe")) return "machine";
  return "person";
}

/**
 * The six mailbox types, in the order the sidebar lists them.
 *
 * newsletters:   editorial or recurring publication content someone subscribed to.
 * promotions:    marketing, offers, product upsell, events, sales.
 * jobs:          applicants, applications, candidate alerts, recruiter outreach, hiring platform mail.
 * calendar:      invitations, updates, and replies generated by a calendar system.
 * notifications: transactional or platform alerts that report something that happened.
 * receipts:      receipts, invoices, payment confirmations, and statements.
 */
export type RuleType = "newsletters" | "promotions" | "jobs" | "calendar" | "notifications" | "receipts";

export const RULE_TYPES: readonly RuleType[] = ["newsletters", "promotions", "jobs", "calendar", "notifications", "receipts"];

// ---- address shape ---------------------------------------------------------------

export function localPartOf(email: string): string {
  return email.toLowerCase().split("@")[0] ?? "";
}

export function domainOf(email: string): string {
  return email.toLowerCase().split("@")[1] ?? "";
}

/** The dot-separated labels of a domain, so a rule can look at "e", "usa", and "experian" separately. */
function labelsOf(domain: string): string[] {
  return domain.split(".").filter(Boolean);
}

/** Freemail providers. The domain is shared by strangers, so only the local part can say who wrote. */
const FREEMAIL = /^(gmail|googlemail|outlook|hotmail|yahoo|ymail|icloud|me|mac|aol|proton|protonmail|live|msn)\.[a-z.]{2,}$/i;

/** Local parts a company hands to software, never to one person. */
const ROLE_LOCAL_PARTS = new Set([
  "no-reply",
  "noreply",
  "notification",
  "notifications",
  "alert",
  "alerts",
  "support",
  "team",
  "hello",
  "hi",
  "info",
  "mail",
  "news",
  "updates",
  "do-not-reply",
  "automated",
  "system",
  "billing",
  "receipts",
  "jobs",
  "careers",
  "talent",
  "recruiting",
]);

/** The local part without its +tag, which is where a list or campaign id is bolted on. */
function baseLocal(email: string): string {
  return localPartOf(email).split("+")[0] ?? "";
}

/**
 * True for an address software writes from. The exact list covers the usual
 * role mailboxes; the separator-stripped test catches every spelling of
 * no-reply, including one buried in a longer word the way gustonoreply@gusto.com
 * buries it, which a prefix test misses.
 */
export function isRoleAddress(email: string): boolean {
  return ROLE_LOCAL_PARTS.has(baseLocal(email)) || isNoReplyAddress(email);
}

/** True when the local part spells no-reply anywhere in it, separators and position aside. */
export function isNoReplyAddress(email: string): boolean {
  const bare = baseLocal(email).replace(/[._-]/g, "");
  return bare.includes("noreply") || bare.includes("donotreply");
}

/** What the rules know about the mailbox owner's own history with a sender. Both fields are optional. */
export interface RuleContext {
  /** Lowercased addresses the owner has sent mail to. */
  knownAddresses?: ReadonlySet<string>;
  /** True when the thread already carries a message the owner sent. */
  threadHasOutbound?: boolean;
}

const REPLY_SUBJECT = /^\s*(re|fwd?)\s*:/i;

/**
 * People beat headers. A List-Id on a message a person wrote is a property of
 * the transport, not of the message: a hiring inbox run as a Google Group
 * stamps List-Id on every applicant's mail, and the old rule filed all of them
 * as newsletters. A role address is never a person, whichever other signal
 * fires, so mail from a group address is still free to take a bulk type.
 */
export function isPersonSender(m: GmailMessage, ctx: RuleContext = {}): boolean {
  const from = fromAddress(m);
  if (!from || isRoleAddress(from)) return false;
  if (FREEMAIL.test(domainOf(from))) return true;
  if (ctx.knownAddresses?.has(from)) return true;
  if (ctx.threadHasOutbound === true) return true;
  return REPLY_SUBJECT.test(header(m, "Subject"));
}

// ---- type signals ----------------------------------------------------------------

const RECEIPT_SUBJECT = /\b(receipt|invoice|your order|order confirmation|payment (received|confirmation)|has been paid|statement is (ready|available))\b/i;
const RECEIPT_SENDERS = /^(receipts?|invoices?|billing|payments?|orders?|no-?reply\+receipts?)@|@(stripe\.com|mercury\.com|paypal\.com|squareup\.com|shopify\.com|amazon\.com)$/i;

/** Subjects calendar systems generate for invitations and replies. */
const CALENDAR_SUBJECT = /^\s*(invitation|updated invitation|accepted|declined|tentatively accepted|tentative|canceled event|cancelled event|new event|event update|reminder)\b/i;
const CALENDAR_SENDERS = /^(calendar-notification@google\.com|calendar-server@|.*@calendar\.google\.com|no-?reply@calendly\.com|.*@cal\.com)$/i;

/** Domains that only ever mail about something that happened in an account or a project. */
const PLATFORM_DOMAINS =
  /(^|\.)(github\.com|slack\.com|notion\.so|linear\.app|figma\.com|render\.com|vercel\.com|atlassian\.(net|com)|asana\.com|calendly\.com|zoom\.us|docusign\.(net|com)|stripe\.com|mercury\.com|facebook\.com|instagram\.com|linkedin\.com|google\.com|experian\.com|dropbox\.com|apple\.com|microsoft\.com|x\.com|twitter\.com|gusto\.com|quickbooks\.com|granola\.ai)$/i;

/** Local parts that announce something rather than sell something. */
const NOTIFIER_LOCAL = /^(notifications?|alerts?|security|system)/i;

/** Hiring platforms. Everything they send is about a role, a candidate, or an application. */
const JOB_PLATFORMS = /(^|\.)(wellfound\.com|angel\.co|greenhouse\.io|lever\.co|ashbyhq\.com|workable\.com|indeed\.com|ziprecruiter\.com|hired\.com|otta\.com|welcometothejungle\.com)$/i;

/** LinkedIn splits its mail by local part; only the jobs addresses are hiring mail. */
const JOB_LINKEDIN = /^(jobs|jobs-noreply|jobs-listings|job-alerts)(@|-)/i;

/** A hiring inbox run as a mailing list, so List-Id names it: <jobs.arcforma.ai>, <careers.example.com>. */
const JOB_LIST_ID = /^\s*<?\s*(jobs|careers|hiring|recruiting|talent)[.@]/i;

const JOB_SUBJECT = new RegExp(
  [
    "\\bapplicants?\\b",
    "\\bapplied (to|for)\\b",
    "\\bapplications?\\b",
    "\\bcandidates?\\b",
    "\\bresum[eé]\\b",
    "\\bcv\\b",
    "\\binterview\\b",
    "\\bjob (opening|alert|posting|post)\\b",
    "\\bopen (role|position|roles|positions)\\b",
    "\\bhiring\\b",
    "\\brecruit(er|ers|ing|ment)\\b",
    "\\bis interested in\\b",
    "\\boffer letter\\b",
  ].join("|"),
  "i"
);

/** Words that only appear when a message is selling. */
const PROMO_SUBJECT = new RegExp(
  [
    "\\b\\d+% off\\b",
    "\\boff (select|your|all)\\b",
    "\\bsave (up to|big|on|\\$|\\d)",
    "\\bsale\\b",
    "\\bdiscount",
    "\\bcoupon\\b",
    "\\bpromo\\b",
    "\\bdeals?\\b",
    "\\boffers\\b",
    "\\b(see|special|exclusive|introductory) offer\\b",
    "\\bfree shipping\\b",
    "\\bnew arrivals?\\b",
    "\\bback in stock\\b",
    "\\bnow trending\\b",
    "\\bshop\\b",
    "\\blast chance\\b",
    "\\blimited time\\b",
    "\\bflash sale\\b",
    "\\bblack friday\\b",
    "\\bcyber monday\\b",
    "\\bearly bird\\b",
    "\\bends (tonight|today|soon)\\b",
    "\\bdon'?t miss\\b",
    "\\byou'?re invited\\b",
    "\\bwebinar\\b",
    "\\bregister (now|today)\\b",
    "\\bregistration is open\\b",
    "\\bsave your (seat|spot)\\b",
    "\\bupgrade (now|today|your)\\b",
    "\\bfor less\\b",
    "\\brefer(ring)? a friend\\b",
    "\\bget paid by referring\\b",
    "\\breferral (bonus|reward)\\b",
    "\\bwhat'?s new (at|in|with)\\b",
    "\\btry .{0,24}for free\\b",
    "\\bopens today\\b",
  ].join("|"),
  "i"
);

/** Address parts that name a shop or a marketing programme rather than a service. */
const PROMO_LABEL = /(^|[.-])(marketing|promo|promos|promotions|offers?|deals?|sales|shopping|retail|ecomm|campaigns?|mkt)([.-]|$)/i;
const PROMO_WORD_IN_LABEL = /(store|shop|outlet|deals)/i;

/** Platforms and address parts that name a publication rather than a product. */
const NEWSLETTER_PLATFORMS = /(^|\.)(substack\.com|beehiiv\.com|ghost\.io|medium\.com|mcsv\.net|convertkit(-mail)?\.com|kit\.com|buttondown\.(email|com)|campaign-archive\.com|mailerlite\.com)$/i;
const EDITORIAL_LABEL = /(^|[.-])(news|newsletter|newsletters|digest|digests|bulletin|press|journal|weekly|daily|dispatch|letter|letters|briefing|reads)([.-]|$)/i;

function anyLabel(email: string, re: RegExp): boolean {
  const local = baseLocal(email);
  return re.test(local) || labelsOf(domainOf(email)).some((l) => re.test(l));
}

/** The sender itself is a shop or a marketing programme. */
function isPromoSender(from: string): boolean {
  return anyLabel(from, PROMO_LABEL) || anyLabel(from, PROMO_WORD_IN_LABEL);
}

/** The sender itself is a publication. */
function isEditorialSender(from: string): boolean {
  return NEWSLETTER_PLATFORMS.test(domainOf(from)) || anyLabel(from, EDITORIAL_LABEL);
}

/**
 * A calendar object alone is not enough: a person who writes "here is the invite" and attaches
 * an .ics is having a conversation, and the thread belongs with them, not under Calendar. Calendar
 * means the message itself is a calendar notice: generated by a calendar system, or carrying an
 * invitation-style subject, or auto-submitted.
 */
export function isCalendarNotice(m: GmailMessage): boolean {
  if (!hasCalendarPart(m.payload)) return false;
  const from = fromAddress(m);
  if (CALENDAR_SENDERS.test(from)) return true;
  if (CALENDAR_SUBJECT.test(header(m, "Subject"))) return true;
  return isAutoGenerated(m);
}

/**
 * First-pass type from headers alone. Null means the rules have no opinion and
 * the local model should decide, which is also the answer when the
 * deterministic signals genuinely disagree: a platform address sending a
 * marketing subject is neither plainly a notification nor plainly a promotion.
 *
 * The order is fixed. Calendar first, because a calendar notice is unmistakable.
 * Then the person override, so nothing a human wrote can be filed as bulk mail.
 * Then receipts, jobs, notifications, promotions, and last newsletters, which
 * is the weakest signal and used to swallow everything carrying a list header.
 */
/** Addresses a company points at hiring. Mail sent to one of them is about hiring, whoever wrote it. */
const HIRING_LOCAL = /^(jobs|careers|hiring|talent|recruiting|recruitment|applications?|apply|resumes?)$/i;

export function isHiringRecipient(m: GmailMessage): boolean {
  const to = `${header(m, "To")}, ${header(m, "Cc")}`;
  for (const match of to.matchAll(/([A-Za-z0-9._%+-]+)@[A-Za-z0-9.-]+/g)) {
    if (HIRING_LOCAL.test(match[1] ?? "")) return true;
  }
  return false;
}

export function ruleType(m: GmailMessage, ctx: RuleContext = {}): RuleType | null {
  if (isCalendarNotice(m)) return "calendar";
  // Mail addressed to a hiring alias is job mail even though a person wrote it. An applicant is a
  // person, so the person rule below would otherwise drop 395 applications into the main flow.
  if (isHiringRecipient(m)) return "jobs";
  if (isPersonSender(m, ctx)) return null;

  const from = fromAddress(m);
  const domain = domainOf(from);
  const subject = header(m, "Subject");
  const listId = header(m, "List-Id");
  // Bulk mail: a managed list, an unsubscribe link, or the sender saying so outright.
  const bulk = Boolean(listId || header(m, "List-Unsubscribe")) || header(m, "Precedence").toLowerCase() === "bulk";

  if (RECEIPT_SENDERS.test(from) || RECEIPT_SUBJECT.test(subject)) return "receipts";

  const promoSender = isPromoSender(from);
  const promotional = promoSender || PROMO_SUBJECT.test(subject);

  const onJobPlatform = JOB_PLATFORMS.test(domain) || (/(^|\.)linkedin\.com$/i.test(domain) && JOB_LINKEDIN.test(from)) || JOB_LIST_ID.test(listId);
  if (onJobPlatform || (JOB_SUBJECT.test(subject) && !promotional)) return "jobs";

  if (PLATFORM_DOMAINS.test(domain)) {
    // A shop that happens to sit on a platform domain is still a shop, so it falls through to
    // promotions. A platform address with a marketing subject is the ambiguous case: no
    // deterministic answer is honest, so the model decides.
    if (!promoSender) return promotional ? null : "notifications";
  } else if ((NOTIFIER_LOCAL.test(baseLocal(from)) || isNoReplyAddress(from)) && !bulk && !isEditorialSender(from) && !promoSender) {
    // Off the known platforms a no-reply address only means "software wrote this". Software sending
    // in bulk is running a campaign, not reporting an event, so that case is left to the rules below.
    return "notifications";
  }

  if (promotional) return "promotions";
  // List-Id names a managed list, which by this point can only be a publication. Bulk mail without
  // one is on every marketing blast, so it needs the sender to look like a publication too.
  if (listId) return "newsletters";
  if (bulk && isEditorialSender(from)) return "newsletters";
  return null;
}
