import { test } from "node:test";
import assert from "node:assert/strict";
import { isAutoGenerated, isNoReplyAddress, isPersonSender, isRoleAddress, normalizeSubject, ruleType, senderType, RULE_TYPES } from "./normalize.js";
import type { GmailMessage } from "./mime.js";

function msg(headers: Record<string, string>, payload: Partial<GmailMessage["payload"]> = {}): GmailMessage {
  return { id: "x", threadId: "x", payload: { mimeType: "text/plain", headers: Object.entries(headers).map(([name, value]) => ({ name, value })), ...payload } };
}

test("normalizeSubject strips stacked reply prefixes", () => {
  assert.equal(normalizeSubject("Re: RE: Fwd: Invoice"), "invoice");
  assert.equal(normalizeSubject(undefined), "");
});

test("isAutoGenerated and senderType follow the mailroom rules", () => {
  assert.equal(isAutoGenerated(msg({ From: "noreply@github.com", Subject: "PR merged" })), true);
  assert.equal(isAutoGenerated(msg({ From: "maya@arcforma.ai", Subject: "Automatic reply: out" })), true);
  assert.equal(isAutoGenerated(msg({ From: "maya@arcforma.ai", Subject: "Kickoff", "Auto-Submitted": "no" })), false);
  assert.equal(senderType(msg({ From: "billing@render.com" })), "role-address");
  assert.equal(senderType(msg({ From: "digest@substack.com", "List-Unsubscribe": "<mailto:x>" })), "machine");
  assert.equal(senderType(msg({ From: "maya@arcforma.ai" })), "person");
});

test("ruleType assigns one of the six types, or nothing", () => {
  assert.deepEqual([...RULE_TYPES], ["newsletters", "promotions", "jobs", "calendar", "notifications", "receipts"]);
  assert.equal(ruleType(msg({ From: "digest@substack.com", "List-Unsubscribe": "<mailto:x>" })), "newsletters");
  assert.equal(ruleType(msg({ From: "notifications@github.com", "List-Unsubscribe": "<mailto:x>" })), "notifications");
  assert.equal(ruleType(msg({ From: "receipts@stripe.com", Subject: "Your receipt from Arcforma" })), "receipts");
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Invitation: Kickoff" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Kickoff" })), null);
  // A person writing "here is the invite" with an .ics attached is a conversation, not a calendar notice.
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Re: Form AI | Schedule your next session" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), null);
  assert.equal(ruleType(msg({ From: "calendar-notification@google.com", Subject: "Re: something" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
  assert.equal(ruleType(msg({ From: "jj@example.com", Subject: "Accepted: Arcforma | JJ @ Tue Sep 1" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
});

test("role addresses: the exact list, plus no-reply wherever it is spelled in the local part", () => {
  for (const a of ["no-reply@x.example", "noreply@x.example", "notifications@x.example", "support@x.example", "jobs@x.example", "talent@x.example", "do-not-reply@x.example"]) {
    assert.equal(isRoleAddress(a), true, a);
  }
  // A prefix test misses these; the mailbox is still software.
  assert.equal(isNoReplyAddress("gustonoreply@gusto.com"), true);
  assert.equal(isNoReplyAddress("newsletters-noreply@linkedin.com"), true);
  assert.equal(isNoReplyAddress("do_not_reply@x.example"), true);
  assert.equal(isRoleAddress("dana@northwind.example"), false);
  assert.equal(isRoleAddress("rowan.hale@vector-labs.example"), false);
});

test("isPersonSender: freemail, an address written to before, an outbound message in the thread, a Re: subject", () => {
  const list = { "List-Id": "<jobs.arcforma.example>", "List-Unsubscribe": "<mailto:x>" };
  assert.equal(isPersonSender(msg({ From: "avery@gmail.com", Subject: "Engineer, available now", ...list })), true, "freemail");
  assert.equal(isPersonSender(msg({ From: "avery@yahoo.co.uk", Subject: "Hello", ...list })), true, "freemail under another country domain");
  assert.equal(isPersonSender(msg({ From: "talent@gmail.com", Subject: "Hello", ...list })), false, "a role local part is never a person");
  assert.equal(isPersonSender(msg({ From: "rowan@vector-labs.example", Subject: "Phase two", ...list })), false, "no signal on its own");
  assert.equal(isPersonSender(msg({ From: "rowan@vector-labs.example", Subject: "Phase two", ...list }), { knownAddresses: new Set(["rowan@vector-labs.example"]) }), true, "Oliver has written to the address");
  assert.equal(isPersonSender(msg({ From: "rowan@vector-labs.example", Subject: "Phase two", ...list }), { threadHasOutbound: true }), true, "Oliver has written in the thread");
  assert.equal(isPersonSender(msg({ From: "rowan@vector-labs.example", Subject: "Re: Phase two", ...list })), true, "a reply prefix");
  assert.equal(isPersonSender(msg({ From: "rowan@vector-labs.example", Subject: "Fwd: Phase two", ...list })), true, "a forward prefix");
});

test("people beat headers: a person's mail never takes a bulk type, whatever the transport stamped on it", () => {
  const list = { "List-Id": "<jobs.arcforma.example>", "List-Unsubscribe": "<mailto:x>" };
  // Oliver's hiring inbox is a Google Group, so every applicant arrives with List-Id set.
  assert.equal(ruleType(msg({ From: "avery@gmail.com", Subject: "AI engineer, LangGraph experience", ...list })), null);
  assert.equal(ruleType(msg({ From: "casey@studio.example", Subject: "client workflow build", ...list })), "jobs", "the same list, from an address with no person signal");
  assert.equal(ruleType(msg({ From: "casey@studio.example", Subject: "Re: client workflow build", ...list })), null, "the reply prefix says a person is writing");
});

test("promotions, jobs, and the ambiguous cases the rules hand to the model", () => {
  const u = { "List-Unsubscribe": "<mailto:x>" };
  assert.equal(ruleType(msg({ From: "shop@nordic-outfitters.example", Subject: "The autumn range", ...u })), "promotions");
  assert.equal(ruleType(msg({ From: "hello@lumen-events.example", Subject: "Register now for the September webinar", ...u })), "promotions");
  assert.equal(ruleType(msg({ From: "microsoftstore@microsoftstore.microsoft.com", Subject: "Get a school-ready Surface", ...u })), "promotions", "a shop on a platform domain is still a shop");
  assert.equal(ruleType(msg({ From: "talent@wellfound.com", Subject: "Avery is interested in AI Engineer", ...u })), "jobs");
  assert.equal(ruleType(msg({ From: "jobs-noreply@linkedin.com", Subject: "12 new roles this week", ...u })), "jobs");
  assert.equal(ruleType(msg({ From: "invitations@linkedin.com", Subject: "See who accepted your invitation", ...u })), "notifications", "the rest of LinkedIn is not hiring mail");
  assert.equal(ruleType(msg({ From: "gustonoreply@gusto.com", Subject: "Your payroll is ready", ...u })), "notifications");
  assert.equal(ruleType(msg({ From: "noreply@news.bloomberg.example", Subject: "Markets Daily", ...u })), "newsletters", "a publication keeps its type through a no-reply address");
  assert.equal(ruleType(msg({ From: "workspace-noreply@google.com", Subject: "Get paid by referring Google Workspace", ...u })), null, "a platform address selling something is the model's call");
  assert.equal(ruleType(msg({ From: "workspace-noreply@google.com", Subject: "Payment failure: Business Standard" })), "notifications", "the same address reporting an event is not");
});

test("mail addressed to a hiring alias is job mail even when a person wrote it", () => {
  const applicant = msg({ From: "sangramjeet47@gmail.com", To: "jobs@arcforma.ai", Subject: "AI and Full-Stack Engineer", "List-Id": "<jobs.arcforma.ai>" });
  assert.equal(ruleType(applicant), "jobs");
  // A person writing to a normal address is still a person, with or without list headers.
  assert.equal(ruleType(msg({ From: "jmolz12@gmail.com", To: "you@example.com", Subject: "client workflow build", "List-Id": "<x.example>" })), null);
  // The alias may sit in Cc, and a display name must not fool the match.
  assert.equal(ruleType(msg({ From: "someone@example.com", To: "you@example.com", Cc: "Careers <careers@arcforma.ai>", Subject: "Application" })), "jobs");
  assert.equal(ruleType(msg({ From: "someone@example.com", To: "jobsworth@example.com", Subject: "Hello there" })), null);
});
