import { test } from "node:test";
import assert from "node:assert/strict";
import { isAutoGenerated, normalizeSubject, ruleType, senderType } from "./normalize.js";
import type { GmailMessage } from "./mime.js";

function msg(headers: Record<string, string>, payload: Partial<GmailMessage["payload"]> = {}): GmailMessage {
  return { id: "x", threadId: "x", payload: { mimeType: "text/plain", headers: Object.entries(headers).map(([name, value]) => ({ name, value })), ...payload } };
}

test("normalizeSubject strips stacked reply prefixes", () => {
  assert.equal(normalizeSubject("Re: RE: Fwd: Invoice"), "invoice");
  assert.equal(normalizeSubject(undefined), "");
});

test("isAutoGenerated and senderType follow the mailroom rules", () => {
  assert.equal(isAutoGenerated(msg({ From: "noreply@github.com", Subject: "PR merged" })), true);
  assert.equal(isAutoGenerated(msg({ From: "maya@arcforma.ai", Subject: "Automatic reply: out" })), true);
  assert.equal(isAutoGenerated(msg({ From: "maya@arcforma.ai", Subject: "Kickoff", "Auto-Submitted": "no" })), false);
  assert.equal(senderType(msg({ From: "billing@render.com" })), "role-address");
  assert.equal(senderType(msg({ From: "digest@substack.com", "List-Unsubscribe": "<mailto:x>" })), "machine");
  assert.equal(senderType(msg({ From: "maya@arcforma.ai" })), "person");
});

test("ruleType assigns newsletters, calendar, notifications, receipts, or nothing", () => {
  assert.equal(ruleType(msg({ From: "digest@substack.com", "List-Unsubscribe": "<mailto:x>" })), "newsletters");
  assert.equal(ruleType(msg({ From: "notifications@github.com", "List-Unsubscribe": "<mailto:x>" })), "notifications");
  assert.equal(ruleType(msg({ From: "receipts@stripe.com", Subject: "Your receipt from Arcforma" })), "receipts");
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Invitation: Kickoff" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Kickoff" })), null);
  // A person writing "here is the invite" with an .ics attached is a conversation, not a calendar notice.
  assert.equal(ruleType(msg({ From: "maya@arcforma.ai", Subject: "Re: Form AI | Schedule your next session" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), null);
  assert.equal(ruleType(msg({ From: "calendar-notification@google.com", Subject: "Re: something" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
  assert.equal(ruleType(msg({ From: "jj@example.com", Subject: "Accepted: Arcforma | JJ @ Tue Sep 1" }, { mimeType: "multipart/mixed", parts: [{ mimeType: "text/calendar" }] })), "calendar");
});
